name = "blog"
compatibility_date = "2025-12-16"
compatibility_flags = ["nodejs_compat"]

# Workers Site 配置（旧版）
[site]
bucket = "./dist"
entry-point = "workers-site"

# 或者新版 Assets 配置
[assets]
directory = "./dist"
bypass_cache = false